version: "3"

services:
  app:
    image: ${APP_NAME}:latest
    build:
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: ${APP_NAME}
    volumes:
      - ./app:/var/app/
      - ./models:/var/app/models/
      - ./static:/var/app/static/
      - ./templates:/var/app/templates/
      - ./filters:/var/app/filters/
      - ./tests:/var/app/tests/
      - ./autonomous/src/autonomous:/var/app/autonomous/
    command: ["/var/app/init.sh"]
    ports:
      - "${APP_PORT}:${COMM_PORT}"
    depends_on:
      - api
      - db
  api:
    image: ${APP_NAME}_api:latest
    build:
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: ${APP_NAME}_api
    volumes:
      - ./api:/var/app/
      - ./models:/var/app/models/
      - ./static:/var/app/static/
      - ./templates:/var/app/templates/
      - ./filters:/var/app/filters/
      - ./tests:/var/app/tests/
      - ./docs:/var/app/docs/
      - ./autonomous/src/autonomous:/var/app/autonomous/
    command: ["gunicorn", "app:create_app()", "-c/var/gunicorn.conf.py"]
    ports:
      - "${API_PORT}:${COMM_PORT}"
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: ${APP_NAME}_db
    env_file: .env
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
    volumes:
      - ./tables:/data/db
  db-express:
    image: mongo-express:latest
    ports:
      - ${DBDEBUG_PORT}:8081
    env_file: .env
    depends_on:
      - db
  tasks:
    image: ${APP_NAME}_tasks:latest
    build:
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: ${APP_NAME}_tasks
    ports:
      - "${EXTERNAL_MONITOR_PORT}:${MONITOR_PORT}"
    volumes:
      - ./tasks:/var/app/
      - ./models:/var/app/models/
      - ./static:/var/app/static/
      - ./tests:/var/app/tests/
      - ./autonomous/src/autonomous:/var/app/autonomous/
    command: ["gunicorn", "app:create_app()", "-c/var/gunicorn.conf.py"]
    depends_on:
      - taskdb
      - db
  taskdb:
    image: redis/redis-stack-server:latest
    container_name: ${APP_NAME}_taskdb
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
networks:
  default:
    name: ${APP_NAME}_net